# Generated by Django 3.1.6 on 2021-02-17 17:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('content', '0002_genericpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_heading', models.CharField(blank=True, max_length=255)),
                ('item_content', wagtail.fields.RichTextField(blank=True)),
                ('item_button_text', models.CharField(blank=True, max_length=255)),
                ('item_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('item_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepageitems', to='content.homepage')),
            ],
        ),
    ]
