# Generated by Django 3.1.6 on 2021-02-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('content', '0004_auto_20210217_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_hero_button_link', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
