# Generated by Django 3.1.6 on 2021-02-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_socialmediasettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'social media accounts'},
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='email',
            field=models.EmailField(default='email@test.com', help_text='Your Contact Email Address', max_length=254),
            preserve_default=False,
        ),
    ]
