# Generated by Django 3.1.6 on 2021-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210217_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='copyright',
            field=models.CharField(blank=True, help_text='Copyright Blurb at bottom of page', max_length=255),
        ),
    ]
