# Generated by Django 4.2.7 on 2023-11-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_socialmediasettings_copyright'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.AlterField(
            model_name='homepageitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
